<?php

namespace ContainerEnMefwy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FIhqHdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fIhq_hd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fIhq_hd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordEncoder' => ['privates', 'App\\Security\\CustomPasswordEncoder', 'getCustomPasswordEncoderService', true],
            'utilisateur' => ['privates', '.errored..service_locator.fIhq_hd.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.fIhq_hd": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'passwordEncoder' => 'App\\Security\\CustomPasswordEncoder',
            'utilisateur' => 'App\\Entity\\Utilisateur',
        ]);
    }
}
