<?php

namespace ContainerEnMefwy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OuiKrHnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OuiKrHn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OuiKrHn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::delete' => ['privates', '.service_locator.0eHhLLJ', 'get_ServiceLocator_0eHhLLJService', true],
            'App\\Controller\\AdminController::edit' => ['privates', '.service_locator.0eHhLLJ', 'get_ServiceLocator_0eHhLLJService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController::show' => ['privates', '.service_locator.p1lgqsW', 'get_ServiceLocator_P1lgqsWService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.KkqsGdd', 'get_ServiceLocator_KkqsGddService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.fIhq_hd', 'get_ServiceLocator_FIhqHdService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminController:delete' => ['privates', '.service_locator.0eHhLLJ', 'get_ServiceLocator_0eHhLLJService', true],
            'App\\Controller\\AdminController:edit' => ['privates', '.service_locator.0eHhLLJ', 'get_ServiceLocator_0eHhLLJService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminController:show' => ['privates', '.service_locator.p1lgqsW', 'get_ServiceLocator_P1lgqsWService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.KkqsGdd', 'get_ServiceLocator_KkqsGddService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.fIhq_hd', 'get_ServiceLocator_FIhqHdService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminController::delete' => '?',
            'App\\Controller\\AdminController::edit' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::new' => '?',
            'App\\Controller\\AdminController::show' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::new' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:delete' => '?',
            'App\\Controller\\AdminController:edit' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:new' => '?',
            'App\\Controller\\AdminController:show' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:new' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
