<?php

namespace ContainerEnMefwy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomPasswordEncoderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\CustomPasswordEncoder' shared autowired service.
     *
     * @return \App\Security\CustomPasswordEncoder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'CustomPasswordEncoder.php';

        return $container->privates['App\\Security\\CustomPasswordEncoder'] = new \App\Security\CustomPasswordEncoder();
    }
}
