<?php

namespace ContainerEnMefwy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fIhq_hd.App\Entity\Utilisateur' shared service.
     *
     * @return \App\Entity\Utilisateur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fIhq_hd": it references class "App\\Entity\\Utilisateur" but no such service exists.');
    }
}
