<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnMefwy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnMefwy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnMefwy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnMefwy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEnMefwy\App_KernelDevDebugContainer([
    'container.build_hash' => 'EnMefwy',
    'container.build_id' => '47537393',
    'container.build_time' => 1713219559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnMefwy');
